### PR TITLE
fixed unclosed html tags

### PR DESCRIPTION
**Pull request by serglopatin**
take a look at the bottom of base.html I commented out broken script element which was not closed. Also there is weird 'document.write' pointing to 'c.mouseflow.com' domain... Probably malicious code, not sure what is that.

### CODE REVIEW

**Comment by seanauriti** [comment]
I added the close script tag, those scripts are ok, analytics...
Layout not fixed yet
image

**Comment by seanauriti** [comment]
@mikeumus says use main-wrapper{ height: calc(100vh -110px); }
Is a better approach

**Comment by seanauriti** [comment]
Feel free to discuss on slack https://coderbounty-slackin.herokuapp.com/

**Comment by serglopatin** [comment]
ok today i will investigate more this issue.

**Comment by seanauriti** [comment]
@serglopatin thanks so much!

**Pull request merged**
