### PR TITLE
Fixed Implement edit profile#22

### PR DESCRIPTION
**Pull request by Dencgik**

### CODE REVIEW

**Comment by seanauriti** [comment]
Looks good... Let me know your coderbounty username and will send the bounty.  
One tweak, let's remove the GitHub link and use allauth for that. 
Thank you!

**Comment by Dencgik** [comment]
@seanauriti "One tweak, let's remove the GitHub link and use allauth for that. "  - Is it part of the original scope?

**Comment by seanauriti** [comment]
@Dencgik it is. Sorry if it wasn't clear. It should only involve adding a link to the github authentication. I'm fine to release the bounty without it and creat another issue...

**Comment by Dencgik** [comment]
@seanauriti What about "creat another issue...". Will you create this issue?

**Pull request merged**
