### PR TITLE
fixed layout in all pages (related to issue #40)

### PR DESCRIPTION
**Pull request by serglopatin**
added the same layout to all pages (except  http://www.coderbounty.com/accounts/login/ - it uses default template from allauth)

### CODE REVIEW

**Comment by seanauriti** [comment]
Still seeing the layout issue 
image

**Comment by serglopatin** [comment]
hmm... the issue is that page doesn't fully fit to the screen? but scroll to the right works?

**Comment by seanauriti** [comment]
Yes, it fits on the homepage and /list after you fixed it.

**Comment by serglopatin** [comment]
I found other unclosed tags in html, for example in base.html at the bottom <script> is not closed. WIll fix it now.

**Pull request merged**
